server.port: 4000
  
logging.level.root: info
logging.level.pl.reactive11.product_calculator: info

spring:
  application:
    name: product-calculator
  datasource:
    url: jdbc:postgresql://postgres:5432/product-calculator
    username: product-calculator
    password: product-calculator
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/dbchangelog.xml
    enabled: true
    parameters:
      catalog-name: product-calculator